'use client';
import Link from 'next/link';
import { Plus, Minus, Trash2, ArrowRight } from 'lucide-react';
import { useStore } from '@/components/store';

export default function CartPage() {
  const { cart, subtotal, delivery, total, setQuantity, removeFromCart } = useStore();
  return <main className="cart-page"><div className="cart-wrap"><section><div className="eyebrow" style={{ color:'var(--sage-light)' }}>YOUR BAG</div><h1 className="font-display">A small order.<br/>A very good idea.</h1>{cart.length ? cart.map((item,i)=><div className="cart-item" key={item.slug}><div className="cart-index">{String(i+1).padStart(2,'0')}</div><div><div className="cart-name">{item.name}</div><div className="cart-meta">{item.quantity} × ₹{item.price}</div><div style={{ display:'flex', gap:6, marginTop:10 }}><button aria-label="Decrease quantity" onClick={()=>setQuantity(item.slug,item.quantity-1)} className="cart-icon"><Minus size={13}/></button><button aria-label="Increase quantity" onClick={()=>setQuantity(item.slug,item.quantity+1)} className="cart-icon"><Plus size={13}/></button><button aria-label={`Remove ${item.name}`} onClick={()=>removeFromCart(item.slug)} className="cart-icon"><Trash2 size={13}/></button></div></div><strong style={{ fontSize:15 }}>₹{item.price*item.quantity}</strong></div>) : <div style={{ padding:'70px 0', color:'var(--sage-light)' }}>Your bag is waiting. Explore the menu and bring something home.</div>}</section><aside className="cart-total-card"><div className="eyebrow">ORDER SUMMARY</div><h2 className="font-display" style={{ marginTop:16 }}>₹{subtotal.toLocaleString('en-IN')}</h2><div className="summary-row"><span>Subtotal</span><span>₹{subtotal.toLocaleString('en-IN')}</span></div><div className="summary-row"><span>Delivery</span><span>{delivery ? `₹${delivery}` : 'FREE'}</span></div><div className="summary-row summary-total"><span>Total</span><span>₹{total.toLocaleString('en-IN')}</span></div><Link href={cart.length ? '/checkout' : '/menu'} className="btn btn-primary" style={{ width:'100%', marginTop:24 }}>{cart.length ? <>CHECKOUT <ArrowRight size={14}/></> : 'EXPLORE MENU'}</Link><Link href="/menu" style={{ display:'block', textAlign:'center', marginTop:22, color:'var(--sage-deep)', fontSize:12 }}>Continue shopping →</Link></aside></div></main>;
}
