'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { CreditCard, Smartphone, Banknote } from 'lucide-react';
import { useStore } from '@/components/store';

export default function CheckoutPage() {
  const { cart, subtotal, delivery, total, clearCart } = useStore();
  const [payment, setPayment] = useState('UPI');
  const [processing, setProcessing] = useState(false);
  const router = useRouter();
  const placeOrder = async (e: React.FormEvent) => { e.preventDefault(); setProcessing(true); await new Promise(r=>setTimeout(r,1100)); const id='TRS-'+Math.floor(1000+Math.random()*8999); localStorage.setItem('tresor-order', JSON.stringify({ id, total, statusIndex:2, createdAt:new Date().toISOString() })); clearCart(); router.push(`/order/${id}`); };
  return <main className="page"><form className="checkout-grid" onSubmit={placeOrder}><section><div className="eyebrow">05 / CHECKOUT</div><h1 className="section-title font-display">Almost there.</h1><div className="field"><label>FULL NAME</label><input required defaultValue="Abhi Sharma" /></div><div className="field"><label>PHONE</label><input required placeholder="+91 9XXXXXXXXX" /></div><div className="field"><label>ADDRESS</label><input required defaultValue="24, Example Street, Bengaluru" /></div><div className="field"><label>DELIVERY INSTRUCTIONS</label><textarea rows={3} placeholder="Leave at the door if unavailable" /></div><div style={{ marginTop:42 }}><div className="eyebrow">PAYMENT</div><div className="payment-options">{([['UPI',Smartphone],['CARD',CreditCard],['PAY AT DOOR',Banknote]] as [string, typeof Smartphone][]).map(([label,Icon])=>{const active=payment===label;return <button type="button" key={String(label)} onClick={()=>setPayment(String(label))} className={`payment-option ${active?'active':''}`}><Icon size={16}/>{label}</button>})}</div></div></section><aside className="checkout-summary"><div className="eyebrow" style={{ color:'var(--sage-light)' }}>YOUR ORDER</div>{cart.length ? cart.map(i=><div className="summary-row" key={i.slug}><span>{i.name} × {i.quantity}</span><span>₹{i.price*i.quantity}</span></div>) : <div style={{ margin:'22px 0', color:'var(--sage-light)', fontSize:12 }}>Your bag is empty.</div>}<div className="summary-row"><span>Delivery</span><span>{delivery ? `₹${delivery}` : 'FREE'}</span></div><div className="summary-row summary-total"><span>TOTAL</span><span>₹{total.toLocaleString('en-IN')}</span></div><button disabled={!cart.length || processing} className="btn btn-secondary" style={{ width:'100%', marginTop:22, opacity: processing? .7 : 1 }}>{processing ? 'PROCESSING…' : `PLACE ORDER · ₹${total.toLocaleString('en-IN')}`}</button><div style={{ marginTop:14, textAlign:'center', fontSize:10, color:'var(--sage-light)' }}>Payment is simulated for this prototype.</div></aside></form></main>;
}
